In [1]:
!pip install tensorflow

  Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Using cached google_auth-2.3.0-py2.py3-none-any.whl (154 kB)
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Using legacy 'setup.py install' for clang, since package 'wheel' is not installed.
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
    Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.2
    Uninstalling typing-extensions-3

You should consider upgrading via the 'C:\workspace\lecture_night\venv_night\Scripts\python.exe -m pip install --upgrade pip' command.


In [2]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [3]:
# tensor : 
# 1. 데이터를 담는 그릇, 변수
# 2. n 차원 수치 데이터를 가지고 있다!
# 3. 숫자 그 자체 일 수도 있고, 이미지 자체 일 수도 있고, 텍스트 자체 일 수도 있습니다.
# 4. 우리가 생각는 어떠한 데이터라도 숫자로 담을 수 있는 데이터 형태
# NumPy의 ndarray라도 비슷하게 생김 -> tensorflow를 생성할 때 ndarray를 사용하기도 합니다.
# tensorflow의 연산 결과를 ndarray로 변환하기도 합니다.
# NumPy의 ndarray랑 Tensorflow의 tensor랑 무슨 차이가 있느냐? ==> tensor는 GPU나 TPU에서 사용할 수 있습니다.

In [4]:
# tensor 생성해보기
# 일반적으로 우리가 직접 tensor 만드는 일은 거의~~~ 없습니다.
# tf.io나 tf.data라는 내장 모듈이 데이터를 가져오고 tensor로 알아서 잘 변환해 줍니다.
# 이렇게 변환된 tensor를 신경망 모델들이 또한 알아서 잘 사용

In [7]:
# scalar는 rank가 0인 tensor! 차원이 존재하지 않기 때문에! 그냥 단지 숫자!
scalar = tf.constant(7)
scalar, type(scalar)

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 tensorflow.python.framework.ops.EagerTensor)

In [8]:
scalar.ndim # ndim은 number of dimentions

0

In [9]:
vector = tf.constant([10, 10])
vector, type(vector)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>,
 tensorflow.python.framework.ops.EagerTensor)

In [10]:
vector.ndim

1

In [11]:
matrix = tf.constant([
    [10, 7],
    [7, 10]
])
matrix, type(matrix)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]])>,
 tensorflow.python.framework.ops.EagerTensor)

In [12]:
matrix.ndim

2

In [13]:
# tensorflow에서는 숫자로 tensor를 생성할 때, 해당 숫자들의 기본 자료형을 지정하지 않으면
# 생성하는 tensor의 숫자를 int32 (정수형일 경우)나 float32 (실수형일 경우) 자료형으로 지정합니다. 

In [15]:
# 이번에는 소수형태로 된 데이터를 가지고 싶다
another_matrix = tf.constant([
    [10, 7],
    [3, 2],
    [8, 9]
])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 8,  9]])>

In [16]:
# 이번에는 소수형태로 된 데이터를 가지고 싶다
another_matrix2 = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
])
another_matrix2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [17]:
another_matrix3 = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
], dtype = tf.float16)
another_matrix3

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [21]:
# shape가 (3, 2, 3)인 tensorflow 만들어 보기! 
# 1 ~ 18인 총 18개 숫자로 만들어 보겠습니다.
# (3, 2, 3)
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ], [
        [7, 8, 9],
        [10, 11, 12]
    ], [
        [13, 14, 15],
        [16, 17, 18]
    ]        
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [20]:
tensor.ndim

3

In [22]:
# scalar, vector, matrix, tensor를 만들어보았다!
# 지금 막 생성한 tensor의 경우 rank 3입니다. 그러나 이 tensor의 차원은 제한이 없습니다. 
# 일반적으로 이야기할 때,
# scalar : 단일 숫자 
# vector : 방향이 있는 숫자
# matrix : 2차원 배열로 이루어진 숫자들
# tensor : n차원 배열로 이루어진 숫자들

In [23]:
# tensor를 생성할 때
# tf.constant()를 사용하는 방법
# tf.Variable()를 사용하는 방법
# 이 두 가지 방법의 차이는 tf.constant()로 만든 tensor는 immutable 즉, 변경 불가!

In [25]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [26]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [28]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [29]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [30]:
# changeable_tensor or unchangeable_tensor ==> 둘 중에 무엇을 사용해야 하나...
# 우리가 직접 tensor를 만들 일은 거의 없고, tensorflow가 알아서 상황에 맞게 만들어 줍니다.

In [31]:
# tensor의 값을 지정해서 생성을 해보았는데, random값을 가진 tensor를 만들어보려고 합니다

In [33]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [34]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [44]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

In [45]:
random_3, random_4, random_3 == random_4, random_1 == random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [131]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
not_shuffled, tf.random.shuffle(not_shuffled)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [10,  7],
        [ 2,  5]])>)

In [164]:
not_shuffled, tf.random.shuffle(not_shuffled, seed = 42)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>)

In [225]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [226]:
tf.ones(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [227]:
tf.zeros(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [235]:
import numpy as np

numpy_A = np.arange(1, 25, dtype = np.float64)
numpy_A, numpy_A.shape

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]),
 (24,))

In [237]:
A = tf.constant(numpy_A, shape = [2, 4, 3], dtype = tf.int16)
A, A.shape, A.ndim

(<tf.Tensor: shape=(2, 4, 3), dtype=int16, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int16)>,
 TensorShape([2, 4, 3]),
 3)

In [238]:
# tensor에서 우리가 얻을 수 있는 정보들!
# shape : 텐서를 이루는 각 차원 각각의 길이
# rank : 텐서 차원들의 갯수 
# Axis (dimension) : 텐서를 이루는 차원 그 각각
# size : 텐서를 이루는 각 숫자들의 총 갯수

In [244]:
# rank_4_tensor를 만들어 주세요!
# 각 요소들을 0이다!
# shape는 (2, 3, 4, 5)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [245]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [247]:
# tensor에서 얻을 수 있는 정보 정리!
print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor).numpy())
print(type(tf.size(rank_4_tensor).numpy()))

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
120
<class 'numpy.int32'>


In [248]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [249]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [250]:
# rank가 2인 tensor를 만들어 보세요! (첫 행은 10, 7을 가지고, 두번째 행은 3, 4)
# 이 텐서에서 각 행의 마지막 값을 가져온다! 7과 4만 있는 결과를 얻어주세요!

In [252]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3, 4]
])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [256]:
rank_2_tensor[:, -1], rank_2_tensor[:, -1].numpy(), type(rank_2_tensor[:, -1].numpy())

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>,
 array([7, 4]),
 numpy.ndarray)

In [257]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... 은 이전에 존재하는 모든 차원들을 유지한다
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

In [258]:
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [259]:
tf.expand_dims(rank_2_tensor, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

In [260]:
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [261]:
# tensor들의 연산!

In [262]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [264]:
tensor + 10, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [269]:
print(tensor * 10)
print(tf.multiply(tensor, 10)) # 연산을 할 때, function을 사용해서 처리하는 것이 처리 속도를 향상시키는 효과가 있다.

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


In [270]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [266]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [271]:
# 머신 러닝을 하게 되면서 아주 일반적으로 사용하는 연산중에 하나가 matrix multiplication
# tf.matmul()
# 
# 법칙 1 : 행렬 연산을 하는 행렬들의 안쪽은 그 숫자들이 같아야 한다.
# (3, 5) @ (3, 5) -> X
# (5, 3) @ (3, 5) -> O
# (3, 5) @ (5, 3) -> O


# 법칙 2 : 행렬 연산의 결과는 바깥쪽 숫자들로 이루어진 행렬이다!
# (5, 3) @ (3, 5) => (5, 5)
# (3, 5) @ (5, 3) => (3, 3)

In [273]:
print(tensor)
tf.matmul(tensor, tensor) # (2, 2) @ (2, 2)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [274]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [275]:
X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [276]:
X @ Y  # (3, 2) @ (3, 2)

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [277]:
# 우리에게 주어진 선택권 2가지!
# 1. 앞에 나온 텐서의 형태를 바꾸어 준다! (3, 2) @ (3, 2) => (2, 3) @ (3, 2) ==> (2, 2)
# 2. 뒤에 나온 텐서의 형태를 바꾸어 준다! (3, 2) @ (3, 2) => (3, 2) @ (2, 3) ==> (3, 3)

In [278]:
# tf.reshape() : 우리가 정의한 shape로 행렬을 바꾸어 주는 역할
# tf.transpose() : 텐서를 이루는 dimension, 즉 axis를 서로 바꾸어 준다!

In [279]:
# 2의 사례
Y, tf.reshape(Y, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

In [280]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [281]:
# 1의 사례
X, tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)

In [282]:
tf.matmul(tf.transpose(X), Y), tf.transpose(X) @ Y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>)

In [285]:
tf.matmul(a = X, b = Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [286]:
# tf.reshape()
# tf.transpose()
# tf.matmul()
# tf.tensordot()

In [287]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [288]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [290]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [291]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [292]:
print(Y)
print(tf.reshape(Y, (2, 3)))
print(tf.transpose(Y))

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [293]:
# data type 변환하기
# tf.cast()

In [294]:
B = tf.constant([1.7, 7.4])
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [295]:
B = tf.cast(B, dtype= tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [296]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [299]:
D = tf.constant([-7, -10])
print(D)
print(tf.abs(D))

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)
tf.Tensor([ 7 10], shape=(2,), dtype=int32)


# 기술 통계
## 최소 최대 평균 합 표준편차 분산 

In [300]:
# aggregation function
# tf.reduce_min()
# tf.reduce_max()
# tf.reduce_mean()
# tf.reduce_sum()
# tf.math.reduce_std()
# tf.math.reduce_variance()

In [302]:
E = tf.constant(np.random.randint(low = 0, high = 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([63, 50, 31,  6, 52, 70, 91, 27, 86, 97, 37, 40, 85, 78, 11, 22, 67,
       50, 75, 69, 96, 33,  1, 23, 46, 68, 83, 35, 96, 99, 79, 93, 16,  7,
       16, 82, 60, 92, 92, 11, 54,  9, 29, 31, 99, 48, 18, 24, 17, 19])>

In [303]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [304]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [314]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=float16, numpy=51.75>

In [306]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2583>

In [311]:
E = tf.cast(E, dtype= tf.float16)

In [312]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float16, numpy=30.88>

In [313]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=953.5>

In [315]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.28505924, 0.2319698 , 0.44970372, 0.16285712, 0.15751817,
       0.69861644, 0.34280166, 0.07046646, 0.72440952, 0.65395948,
       0.06960256, 0.79357841, 0.42340697, 0.14566769, 0.21268212,
       0.86057045, 0.77824709, 0.78560065, 0.27690278, 0.8436148 ,
       0.16148872, 0.4101468 , 0.64296355, 0.73721266, 0.80953958,
       0.98491442, 0.16478023, 0.60736776, 0.39977131, 0.45188809,
       0.58638301, 0.43121625, 0.0627936 , 0.79323837, 0.94178064,
       0.03056542, 0.25423099, 0.09021743, 0.50846048, 0.68012411,
       0.49020759, 0.36444145, 0.91613216, 0.45379857, 0.2980967 ,
       0.98657201, 0.209609  , 0.84458765, 0.85082714, 0.90393934])>

In [317]:
tf.reduce_max(F), tf.argmax(F)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.9865720095317219>,
 <tf.Tensor: shape=(), dtype=int64, numpy=45>)

In [318]:
tf.reduce_min(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.030565416805954704>,
 <tf.Tensor: shape=(), dtype=int64, numpy=35>)

In [321]:
# tensor를 활용한 연산에서 얻을 수 있는 정보
print(tf.argmax(F).numpy())
print(tf.reduce_max(F).numpy())
print(F[tf.argmax(F)].numpy())
print(F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy())

45
0.9865720095317219
0.9865720095317219
True


In [322]:
# tensor의 축을 추가해보았습니다! expand
# 축을 줄여보고자 한다!
# tf.squeeze() : 텐서의 축, 차원이 1이면 없앤다.

In [324]:
G = tf.constant(np.random.randint(0, 100, 50), shape = (1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [325]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [332]:
some_list = [0, 1, 2, 3]

In [333]:
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [4]:
tf.one_hot(some_list, depth=4, on_value="On", off_value="Off")

NameError: name 'some_list' is not defined

In [5]:
# tf.square()
# tf.sqrt()
# tf.math.log()

In [6]:
import tensorflow as tf
import numpy as np

In [7]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [8]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [9]:
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [10]:
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [11]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [12]:
H = tf.cast(H, dtype=tf.float16)
H

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>

In [13]:
tf.sqrt(H)


<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [14]:
H = tf.cast(H, dtype=tf.float64)
H

<tf.Tensor: shape=(9,), dtype=float64, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.])>

In [15]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])>

In [16]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])>

In [17]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [18]:
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [19]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [20]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [21]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [22]:
# tensor와 NumPy의 관계!
# np.array() : tensor를 ndarray형태로 바꾼다!
# tensor.numpy() : ndarray형태 바꾸기 위해 tensor를 호출

In [23]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [24]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [25]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [26]:
# tensor의 기본 자료형과 NumPy의 기본 자료형을 비교

In [27]:
# tensor는 기본 자료형이 float32, NumPy의 기본 자료형은 float64
# tensorflow에서 neural network를 사용할 때 float32도 충분하다!

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [28]:
x = tf.constant(np.arange(10, 20))
y = tf.constant(np.arange(30, 40))

In [29]:
def function(x, y):
    return x ** 2 + y

function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([130, 152, 176, 202, 230, 260, 292, 326, 362, 400])>

In [30]:
@tf.function  # decorate
def function(x, y):
    return x ** 2 + y

function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([130, 152, 176, 202, 230, 260, 292, 326, 362, 400])>

In [31]:
# 파이썬 중급 => decorator, concurrent 등등

In [32]:
import tensorflow as tf
print(tf.config.list_physical_devices("GPU"))

[]


In [33]:
!nvidia-smi

Tue Oct 26 21:07:20 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 471.11       Driver Version: 471.11       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:06:00.0  On |                  N/A |
|  0%   45C    P8    21W / 175W |   1400MiB /  8192MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------